### ISSUE TITLE
Select all button is slightly too big on mobile

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#183]
![img_4268](https://cloud.githubusercontent.com/assets/1060/21540193/8fea7618-cda5-11e6-9438-f68d80ddd5e3.PNG)

Should be the same size as all the other menu bar buttons

**Comment by andrew** [comment]
Fixed by #184

**Comment by knolleary** [comment]
![screenshot_20170103-003332](https://cloud.githubusercontent.com/assets/51083/21598029/5e68ae16-d14c-11e6-92c2-94085c858e69.png)

Still an issue for me - Chrome/Android

**Comment by briannelson** [comment]
I think we'll have to use a custom checkbox solution like in wtfforms.com

**Comment by andrew** [comment]
@knolleary is this still happening for you?

**Comment by knolleary** [comment]
Yes

![img_20170927_165453](https://user-images.githubusercontent.com/51083/30923790-c2efead6-a3a4-11e7-8b6c-63e6e5f0fb36.jpg)

**Comment by andrew** [comment]
Inadvertently fixed by #366

**Comment by knolleary** [comment]
+💯  for inadvertent fixes 👍
