### ISSUE TITLE
Version number doesn't appear when running in docker image

### ISSUE THREAD

**Issue by gep13** [octobox/octobox#548]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

When running Octobox in a docker image, the version number (which is meant to appear in the settings page, doesn't appear.  This is because in order for this number to appear, the .git folder is required.  However, the docker image explicitly excludes this .git folder, therefore the version number doesn't appear.

This was discussed in detail in this issue: https://github.com/octobox/octobox/issues/503#issuecomment-368248742

🎯 **Goal**

I want to know what version of Octobox is running in my docker image, so that I know if I need to update or not.

💡 **Possible solutions**

Update the docker image file to not exclude the .git folder.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
@gep13 I just pushed a fix to master for this, can you try it out with the latest docker image once it finishes building?

**Comment by gep13** [comment]
@andrew so, I am going to be honest...

I am still not 100% clear on what I need to do in order to run the latest version of the Docker image :sad:

I have fetched the latest code, and I have tried running the application again, however, I am not seeing the version number, so I think I must still be doing something wrong.

Any pointers?

Thanks

**Comment by gep13** [comment]
@andrew I can now confirm that this is all working 😄 

I can now see the version SHA in the Settings screen:

![image](https://user-images.githubusercontent.com/1271146/37257657-6654d0ba-2564-11e8-8e08-e6054366bee6.png)

I was able to get this working after @agc93 pointed me in the right direction.

I had to do the following:

`docker-compose pull app`  - which downloads the latest image that you have pushed to docker hub
`docker-compose up` - to update my instance of the app container to use the new latest version of the image

With that done, everything worked as expected.
